version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/hospital_tasks
      - JWT_SECRET=change_me_in_production
      - JWT_EXPIRES=15m
      - REFRESH_TOKEN_SECRET=change_me_too_in_production
      - REFRESH_TOKEN_EXPIRES=7d
      - NODE_ENV=production
      - SITE_TZ=Asia/Kolkata
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: --replSet rs0
    restart: unless-stopped

  worker:
    build: .
    command: node worker/agenda.js
    environment:
      - MONGODB_URI=mongodb://mongo:27017/hospital_tasks
      - JWT_SECRET=change_me_in_production
      - REFRESH_TOKEN_SECRET=change_me_too_in_production
    depends_on:
      - mongo
    restart: unless-stopped

volumes:
  mongo_data:
